<?php
namespace View\Users;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Tchat</title>
    <base href="/"/>


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">



    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" class="init">
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
</head>
<body>
<header>
    <h1>Exemple de tchat</h1>
</header>



<h2>Users</h2>
<table id="table_id" class="display">
    <thead>
    <tr>
        <th>username</th>
        <th>email</th>
        <th>created</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($this->users as $user) :?>
        <tr>
            <td><?php echo $user->username; ?></td>
            <td><?php echo $user->email; ?></td>
            <td><?php echo $user->created_at; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


<footer>
    <p>Footer.</p>
</footer>
</body>


</html>