<?php
namespace View\Index;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Tchat</title>
    <base href="/"/>
   <!-- Bootstrap CSS --><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<header>
    <h1>Exemple de tchat</h1>
</header>
<h2>Inscription</h2>
<form enctype="multipart/form-data" action="/utilisateurs/inscription" method="post">
    <div class="form-group">
        <label for="exampleInputEmail1">Pseudo</label>
        <input type="text" name="user_name" class="form-control" placeholder="Pseudo">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Email </label>
        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Entre votre email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <input type="submit" value="Submit">
</form>
<footer>
</footer>
</body>
</html>