<?php
namespace View\Salon;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Tchat</title>
    <META HTTP-EQUIV="refresh" CONTENT="4;">
    <base href="/"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<header>
    <h1>Exemple de tchat</h1>
</header>



<h2>Messages</h2>
<table class="table">
    <thead>
    <tr>
        <th scope="col">User</th>
        <th scope="col">Date</th>
        <th scope="col">Message</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($this->messages as $message) :?>
        <tr>
            <td><?php
                echo $message->getUser()->getUsername(); ?></td>
            <td><?php echo $message->getUser()->getCreated()->format('Y-m-d'); ?></td>
            <td><?php echo nl2br($message->getMessage()); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td>
            <form enctype="multipart/form-data" method="post">
                    <label for="exampleInputPassword1">Message</label>
                <textarea name="message"></textarea>
                <input type="submit" value="Submit">
            </form>
        </td>
    </tr>
    </tfoot>
</table>


<footer>
    <p>Footer.</p>
</footer>
</body>


</html>